name: github-actions-pipeline

on: push

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Build
        run: go build 

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
  test:
   needs: build
   runs-on: ubuntu-latest
   steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      - 
        name: Run Unit Tests
        run: go test 

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - 
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: aditisoori/github-actions-pipeline
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha  
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          args: |
            --platform=linux/arm64
            --build-arg=HTTP_PORT=8080
            --build-arg=TCP_PORT=80
          




    


