name: github-actions-pipeline

on: push

jobs:
  test:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v4
   - name: Run Unit Tests
     run: go test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
           ${{env.VERSION_TAG}}
           ${{env.LASTEST_TAG}}


